In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("ceny.txt", sep=";", na_values=['None'], usecols=range(0,9))
df

              EAN  ... PolskiKoszyk
0   5908230514340  ...         4.42
1   5900531001031  ...         2.07
2   5900512300108  ...         4.99
3   5900012000232  ...         7.11
4   5900820000011  ...         3.55
5   5902180020104  ...         3.35
6   5902172000114  ...         3.37
7   5900617014764  ...         4.68
8   5900820005504  ...         5.28
9   5900049816608  ...         5.87
10  5900085011012  ...         6.75
11  5900820012229  ...         3.06
12  5410033851336  ...        16.56
13  5901588016016  ...         3.91
14  5900861430020  ...         6.99
15  5901597860433  ...         4.36
16       59030133  ...         2.51
17  5901630000208  ...         2.42
18  5902020163213  ...          NaN
19  7613031918881  ...        21.05
20  5901154041497  ...         7.44
21  5900397006744  ...         4.19
22  8004260434898  ...        11.86
23  5900541000000  ...         2.39
24  5900197013065  ...          NaN
25  5900020000774  ...         4.82
26  5900437005133  ...        15.62

[27 rows x 9 columns]